apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# if everything for nginx is in default namespace, omit namespace
# or set namespace: default explicitly if you prefer
namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - nginx-demo-app.yaml
  - nginx-demo-ingress.yaml

