apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-11-13T19:24:36Z"
  labels:
    kubernetes.io/metadata.name: ingress-nginx
  name: ingress-nginx
  resourceVersion: "5797"
  uid: 0b58dcbe-69a3-4115-ae18-30eea38068b0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
