apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

generatorOptions:
  disableNameSuffixHash: true

resources:
  - argocd-root.yaml
  - argocd-ingress.yaml

secretGenerator:
  - name: argocd-tls
    type: "kubernetes.io/tls"
    files:
      - tls.crt=../certs/wildcard.localtest.me.pem
      - tls.key=../certs/wildcard.localtest.me-key.pem
